### PR TITLE
Make pyserial-asyncio work on windows without crashing

### LINKED ISSUE #10: Assertion Problems On Windows
We have a case where we hit this assertion on windows: https://github.com/pyserial/pyserial-asyncio/blob/master/serial_asyncio/__init__.py#L121

Can somebody explain the rational behind this assertion to me? n == 0 seems totally legit. Internally, os.write is called which may return 0. This seems to never happen on linux but on windows. 

In my opinion the assert should be like this:
`assert n >= 0 < len(data)`

Same probably applies to this line: https://github.com/pyserial/pyserial-asyncio/blob/master/serial_asyncio/__init__.py#L262

### PR DESCRIPTION
**Pull request by jabdoa2**
Workaround for https://github.com/pyserial/pyserial/issues/162. Fixes #10

### CODE REVIEW

**Comment by zsquareplusc** [comment]
This pull request looks more like adding support for Windows than anything what the title says. May it should be renamed. And could you try a "rebase" and squash the commits into one or a few ones. Otherwise all those tries are forever in the history ;-)

**Comment by jabdoa2** [comment]
@zsquareplusc we have been shipping this as a submodule with the Mission Pinball Framework for a month now. It works perfectly for our users. Would be cool if we can merge this soon.

**Comment by jabdoa2** [comment]
Should i rebase this to make it mergeable? Or is there no interest in this?

**Comment by SzieberthAdam** [comment]
I have.

**Comment by jabdoa2** [comment]
see #13 for a better version

**Pull request closed without merging**
