### PR TITLE
Fixes #17 adds socket support

### LINKED ISSUE #17: Socket support
When passing in `socket://127.0.0.1:9999` as port to `create_serial_connection` to connect an [EchoServerClientProtocol](https://docs.python.org/3/library/asyncio-protocol.html#tcp-echo-server-protocol) an `AttributeError` is thrown on accessing `self._serial.fd`.

```
File "/usr/local/lib/python3.5/site-packages/serial/aio.py", line 260, in _ensure_reader
    self._loop.add_reader(self._serial.fd, self._read_ready)
AttributeError: 'Serial' object has no attribute 'fd'
```

### PR DESCRIPTION
**Pull request by iiSeymour**
Adds socket support and changes the tests to use sockets by default so they now pass under travis.

### CODE REVIEW

**Comment by iiSeymour** [comment]
Good point, I've removed the `baudrate` args.

**Comment by rob-smallshire** [comment]
This looks good. Thank you for your contribution.

I'll look it over again tomorrow with fresh eyes and likely merge it.

**Comment by iiSeymour** [comment]
Great 👍 if it does get merged would you mind doing a release as this will make writting tests much easier.

**Comment by rsebille** [comment]
Indeed, a new version with this in it would be very much appreciated :).

**Comment by zsquareplusc** [comment]
OK, i've uploaded v0.4 to pypi

**Pull request merged**
